{
  "titleOnly": true,
  "types": [
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "test",
    "chore",
    "ci",
    "perf",
    "revert"
  ],
  "scopes": [
    "cli",
    "bulletin",
    "auth",
    "register",
    "content",
    "pop",
    "lookup",
    "deps",
    "ci",
    "release"
  ]
}