// Auto-generated by cdm install -- do not edit
import type { HexString, SizedHex } from "polkadot-api";

declare module "@dotdm/cdm" {
    interface CdmContracts {
        "@dotns/registrar-controller": {
            methods: {
                DEFAULT_ADMIN_ROLE: { args: []; response: SizedHex<32> };
                MAX_ALLOWED_COMMITMENT_AGE: { args: []; response: bigint };
                UPGRADE_INTERFACE_VERSION: { args: []; response: string };
                available: { args: [label: string]; response: boolean };
                commit: { args: [commitment: SizedHex<32>]; response: undefined };
                commitments: { args: [hash: SizedHex<32>]; response: bigint };
                getRoleAdmin: { args: [role: SizedHex<32>]; response: SizedHex<32> };
                grantRole: { args: [role: SizedHex<32>, account: HexString]; response: undefined };
                hasRole: { args: [role: SizedHex<32>, account: HexString]; response: boolean };
                initialize: { args: [registry: HexString, minAge: bigint, maxAge: bigint]; response: undefined };
                isWhiteListed: { args: [who: HexString]; response: boolean };
                makeCommitment: { args: [registration: { label: string; owner: HexString; secret: SizedHex<32>; reserved: boolean }]; response: SizedHex<32> };
                maxCommitmentAge: { args: []; response: bigint };
                minCommitmentAge: { args: []; response: bigint };
                owner: { args: []; response: HexString };
                protocolRegistry: { args: []; response: HexString };
                proxiableUUID: { args: []; response: SizedHex<32> };
                register: { args: [registration: { label: string; owner: HexString; secret: SizedHex<32>; reserved: boolean }]; response: undefined };
                registerReserved: { args: [registration: { label: string; owner: HexString; secret: SizedHex<32>; reserved: boolean }]; response: undefined };
                renounceOwnership: { args: []; response: undefined };
                renounceRole: { args: [role: SizedHex<32>, callerConfirmation: HexString]; response: undefined };
                revokeRole: { args: [role: SizedHex<32>, account: HexString]; response: undefined };
                setRole: { args: [role: SizedHex<32>, account: HexString, enabled: boolean]; response: undefined };
                supportsInterface: { args: [interfaceId: SizedHex<4>]; response: boolean };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                upgradeToAndCall: { args: [newImplementation: HexString, data: Uint8Array]; response: undefined };
                version: { args: []; response: string };
                whiteList: { args: [user: HexString]; response: boolean };
                whiteListAddress: { args: [who: HexString, whiteListStatus: boolean]; response: undefined };
            };
        };
        "@dotns/registrar": {
            methods: {
                UPGRADE_INTERFACE_VERSION: { args: []; response: string };
                addController: { args: [controller: HexString]; response: undefined };
                approve: { args: [to: HexString, tokenId: bigint]; response: undefined };
                available: { args: [id: bigint]; response: boolean };
                balanceOf: { args: [owner: HexString]; response: bigint };
                controllers: { args: [controller: HexString]; response: boolean };
                exists: { args: [tokenId: bigint]; response: boolean };
                getApproved: { args: [tokenId: bigint]; response: HexString };
                initialize: { args: [name: string, symbol: string, registry: HexString]; response: undefined };
                isApprovedForAll: { args: [owner: HexString, operator: HexString]; response: boolean };
                labelOf: { args: [tokenId: bigint]; response: string };
                name: { args: []; response: string };
                owner: { args: []; response: HexString };
                ownerOf: { args: [tokenId: bigint]; response: HexString };
                protocolRegistry: { args: []; response: HexString };
                proxiableUUID: { args: []; response: SizedHex<32> };
                quoteTransferFee: { args: [tokenId: bigint, to: HexString]; response: bigint };
                register: { args: [id: bigint, owner: HexString, label: string]; response: undefined };
                removeController: { args: [controller: HexString]; response: undefined };
                renounceOwnership: { args: []; response: undefined };
                safeTransferFrom: { args: [from: HexString, to: HexString, tokenId: bigint]; response: undefined };
                safeTransferFrom: { args: [from: HexString, to: HexString, tokenId: bigint, data: Uint8Array]; response: undefined };
                setApprovalForAll: { args: [operator: HexString, approved: boolean]; response: undefined };
                supportsInterface: { args: [interfaceId: SizedHex<4>]; response: boolean };
                symbol: { args: []; response: string };
                tokenURI: { args: [tokenId: bigint]; response: string };
                transferFrom: { args: [from: HexString, to: HexString, tokenId: bigint]; response: undefined };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                upgradeToAndCall: { args: [newImplementation: HexString, data: Uint8Array]; response: undefined };
                version: { args: []; response: string };
            };
        };
        "@dotns/registry": {
            methods: {
                UPGRADE_INTERFACE_VERSION: { args: []; response: string };
                initialize: { args: [registry: HexString]; response: undefined };
                owner: { args: [node: SizedHex<32>]; response: HexString };
                owner: { args: []; response: HexString };
                protocolRegistry: { args: []; response: HexString };
                proxiableUUID: { args: []; response: SizedHex<32> };
                recordExists: { args: [node: SizedHex<32>]; response: boolean };
                renounceOwnership: { args: []; response: undefined };
                resolver: { args: [node: SizedHex<32>]; response: HexString };
                setOwner: { args: [node: SizedHex<32>, newOwner: HexString]; response: undefined };
                setResolver: { args: [node: SizedHex<32>, newResolver: HexString]; response: undefined };
                setSubnodeOwner: { args: [record: { parentNode: SizedHex<32>; subLabel: string; parentLabel: string; owner: HexString }]; response: SizedHex<32> };
                setSubnodeResolver: { args: [record: { parentNode: SizedHex<32>; subLabel: string; parentLabel: string; resolver: HexString }]; response: undefined };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                upgradeToAndCall: { args: [newImplementation: HexString, data: Uint8Array]; response: undefined };
                version: { args: []; response: string };
            };
        };
        "@dotns/pop-rules": {
            methods: {
                MAX_RESERVATION_TIME: { args: []; response: bigint };
                UPGRADE_INTERFACE_VERSION: { args: []; response: string };
                classifyName: { args: [name: string]; response: { requirement: number; message: string } };
                getBaseNameReservation: { args: [baseName: string]; response: { reservationOwner: HexString; expiryTimestamp: bigint } };
                initialize: { args: [_startingPrice: bigint, registry: HexString]; response: undefined };
                isBaseName: { args: [baseName: string]; response: boolean };
                isBaseNameReserved: { args: [baseName: string]; response: { isReserved: boolean; reservationOwner: HexString; expiryTimestamp: bigint } };
                owner: { args: []; response: HexString };
                price: { args: [name: string]; response: bigint };
                priceWithCheck: { args: [name: string, userAddress: HexString]; response: { price: bigint; status: number; userStatus: number; message: string } };
                priceWithoutCheck: { args: [name: string, userAddress: HexString]; response: { price: bigint; status: number; userStatus: number; message: string } };
                protocolRegistry: { args: []; response: HexString };
                proxiableUUID: { args: []; response: SizedHex<32> };
                reachFee: { args: [name: string, account: HexString]; response: bigint };
                releaseBaseName: { args: [stem: string]; response: undefined };
                releaseReservationForReclaim: { args: [stem: string, expectedOwner: HexString]; response: undefined };
                renounceOwnership: { args: []; response: undefined };
                reservations: { args: [baseName: string]; response: { owner: HexString; expires: bigint; controller: HexString } };
                reserveBaseName: { args: [stem: string, userAddress: HexString]; response: undefined };
                reserveBaseNameForPop: { args: [stem: string, userAddress: HexString]; response: undefined };
                startingPrice: { args: []; response: bigint };
                stripDigits: { args: [name: string]; response: string };
                supportsInterface: { args: [interfaceId: SizedHex<4>]; response: boolean };
                transferFloor: { args: [name: string, from: HexString, to: HexString]; response: bigint };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                updateStartingPrice: { args: [newStartingPrice: bigint]; response: undefined };
                upgradeToAndCall: { args: [newImplementation: HexString, data: Uint8Array]; response: undefined };
                version: { args: []; response: string };
            };
        };
        "@dotns/resolver": {
            methods: {
                UPGRADE_INTERFACE_VERSION: { args: []; response: string };
                addressOf: { args: [node: SizedHex<32>]; response: HexString };
                initialize: { args: [registry: HexString]; response: undefined };
                owner: { args: []; response: HexString };
                protocolRegistry: { args: []; response: HexString };
                proxiableUUID: { args: []; response: SizedHex<32> };
                renounceOwnership: { args: []; response: undefined };
                setAddress: { args: [node: SizedHex<32>, value: HexString]; response: undefined };
                supportsInterface: { args: [interfaceId: SizedHex<4>]; response: boolean };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                upgradeToAndCall: { args: [newImplementation: HexString, data: Uint8Array]; response: undefined };
                version: { args: []; response: string };
            };
        };
        "@dotns/reverse-resolver": {
            methods: {
                UPGRADE_INTERFACE_VERSION: { args: []; response: string };
                claimReverseRecord: { args: [label: string]; response: undefined };
                initialize: { args: [registry: HexString]; response: undefined };
                nameOf: { args: [addr: HexString]; response: string };
                owner: { args: []; response: HexString };
                protocolRegistry: { args: []; response: HexString };
                proxiableUUID: { args: []; response: SizedHex<32> };
                renounceOwnership: { args: []; response: undefined };
                setReverseName: { args: [addr: HexString, name: string]; response: undefined };
                supportsInterface: { args: [interfaceId: SizedHex<4>]; response: boolean };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                upgradeToAndCall: { args: [newImplementation: HexString, data: Uint8Array]; response: undefined };
                version: { args: []; response: string };
            };
        };
        "@dotns/content-resolver": {
            methods: {
                UPGRADE_INTERFACE_VERSION: { args: []; response: string };
                contenthash: { args: [node: SizedHex<32>]; response: Uint8Array };
                initialize: { args: [registry: HexString]; response: undefined };
                isApprovedForAll: { args: [owner: HexString, operator: HexString]; response: boolean };
                owner: { args: []; response: HexString };
                protocolRegistry: { args: []; response: HexString };
                proxiableUUID: { args: []; response: SizedHex<32> };
                renounceOwnership: { args: []; response: undefined };
                setApprovalForAll: { args: [operator: HexString, approved: boolean]; response: undefined };
                setContenthash: { args: [node: SizedHex<32>, hash: Uint8Array]; response: undefined };
                setText: { args: [node: SizedHex<32>, key: string, value: string]; response: undefined };
                supportsInterface: { args: [interfaceId: SizedHex<4>]; response: boolean };
                text: { args: [node: SizedHex<32>, key: string]; response: string };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                upgradeToAndCall: { args: [newImplementation: HexString, data: Uint8Array]; response: undefined };
                version: { args: []; response: string };
            };
        };
        "@dotns/store-factory": {
            methods: {
                claimUserStore: { args: []; response: HexString };
                deployLabelStoreFor: { args: [user: HexString]; response: HexString };
                getLabelStore: { args: [user: HexString]; response: HexString };
                getLabelStoreCount: { args: []; response: bigint };
                getLabelStores: { args: [offset: bigint, limit: bigint]; response: HexString[] };
                getUserStore: { args: [user: HexString]; response: HexString };
                getUserStoreCount: { args: []; response: bigint };
                getUserStores: { args: [offset: bigint, limit: bigint]; response: HexString[] };
                labelStoreBeacon: { args: []; response: HexString };
                owner: { args: []; response: HexString };
                protocolRegistry: { args: []; response: HexString };
                renounceOwnership: { args: []; response: undefined };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                upgradeLabelStoreImplementation: { args: [newImplementation: HexString]; response: undefined };
                upgradeUserStoreImplementation: { args: [newImplementation: HexString]; response: undefined };
                userStoreBeacon: { args: []; response: HexString };
                version: { args: []; response: string };
            };
        };
        "@dotns/multicall3": {
            methods: {
                aggregate: { args: [calls: { target: HexString; callData: Uint8Array }[]]; response: { blockNumber: bigint; returnData: Uint8Array[] } };
                aggregate3: { args: [calls: { target: HexString; allowFailure: boolean; callData: Uint8Array }[]]; response: { success: boolean; returnData: Uint8Array }[] };
                aggregate3Value: { args: [calls: { target: HexString; allowFailure: boolean; value: bigint; callData: Uint8Array }[]]; response: { success: boolean; returnData: Uint8Array }[] };
                blockAndAggregate: { args: [calls: { target: HexString; callData: Uint8Array }[]]; response: { blockNumber: bigint; blockHash: SizedHex<32>; returnData: { success: boolean; returnData: Uint8Array }[] } };
                getBasefee: { args: []; response: bigint };
                getBlockHash: { args: [blockNumber: bigint]; response: SizedHex<32> };
                getBlockNumber: { args: []; response: bigint };
                getChainId: { args: []; response: bigint };
                getCurrentBlockCoinbase: { args: []; response: HexString };
                getCurrentBlockDifficulty: { args: []; response: bigint };
                getCurrentBlockGasLimit: { args: []; response: bigint };
                getCurrentBlockTimestamp: { args: []; response: bigint };
                getEthBalance: { args: [addr: HexString]; response: bigint };
                getLastBlockHash: { args: []; response: SizedHex<32> };
                tryAggregate: { args: [requireSuccess: boolean, calls: { target: HexString; callData: Uint8Array }[]]; response: { success: boolean; returnData: Uint8Array }[] };
                tryBlockAndAggregate: { args: [requireSuccess: boolean, calls: { target: HexString; callData: Uint8Array }[]]; response: { blockNumber: bigint; blockHash: SizedHex<32>; returnData: { success: boolean; returnData: Uint8Array }[] } };
            };
        };
    }
}
